version: '3.8'
services:
  app:
    image: libanmo/spring-app:late # Use the latest tag or specify a version
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/personpool
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
  app-frontend:
    image: libanmo/frontend-app:one
    ports:
      - "8082:80"
    # Adjust if necessary
  db:
    image: postgres
    environment:
      POSTGRES_DB: personpool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
